import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {Box, Button,Stack,Group,Text, Anchor, SimpleGrid} from "@mantine/core"
import GetChallanDetails from "@/components/GetChallanDetails";
const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  const navlinks = ["about eChallen","eChallen benefits","FAQs"]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<main style={{height:"100%",width:"100%",maxWidth:"1600px"}}>
<Stack gap="0px" h="100%" w="100%" >
  
<Group justify="space-between" px="20px" py="20px" >
  
<Text ff="Roboto" fz="32px" fw="400" >
  Logo
</Text>

<Text ff="Roboto" fz="36px" fw="400">
  Goverment of Country
</Text>

</Group>
<Group py="10" px="15" bg="blue">
  
{
navlinks.map((navlink,index)=><Anchor ff="Roboto" fz="18px" c="white"  key={index}>
  {navlink}
</Anchor>)

}

</Group>

<Stack w="100%"  py="20px" px="20px" justify="center"  align="center" >

  <GetChallanDetails/>
</Stack>


</Stack>

</main>
    </>
  );
}
